name: Build & Release Electron App
# 触发规则：推送tag时执行（版本发布标准流程）
on:
  push:
    tags:
      - 'v*' # 推送 v1.0.0 这类标签才打包发布
  # 可选：手动触发
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build Windows Installer
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run dist

#  build-macos:
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'npm'
#      - name: Install dependencies
#        run: npm ci
#      - name: Build Mac DMG/Zip
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#        run: npm run dist
#
#  build-linux:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Setup Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: 'npm'
#      - name: Install system libs
#        run: sudo apt-get install libopenjp2-7 libxcb-damage0
#      - name: Install dependencies
#        run: npm ci
#      - name: Build Linux Deb/AppImage
#        env:
#          GH_TOKEN: ${{ secrets.GH_TOKEN }}
#        run: npm run dist